2025-01-04 21:34:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "CREATE TABLE BOLETA (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador de la boleta',\000d\000a    NUMBER_TICKET int  NOT NULL COMMENT 'numero de la boleta',\000d\000a    DOCUMENTO_VENTA_ID int  NOT NULL,\000d\000a    CONSTRAINT BOLETA_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'datos de la boleta'"
Syntax error in SQL statement "CREATE TABLE BOLETA (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador de la boleta',\000d\000a    NUMBER_TICKET int  NOT NULL COMMENT 'numero de la boleta',\000d\000a    DOCUMENTO_VENTA_ID int  NOT NULL,\000d\000a    CONSTRAINT BOLETA_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'datos de la boleta'"; SQL statement:
CREATE TABLE BOLETA (
    ID int  NOT NULL auto_increment COMMENT 'identificador de la boleta',
    NUMBER_TICKET int  NOT NULL COMMENT 'numero de la boleta',
    DOCUMENTO_VENTA_ID int  NOT NULL,
    CONSTRAINT BOLETA_pk PRIMARY KEY (ID)
) COMMENT 'datos de la boleta' [42000-214]
2025-01-04 21:34:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: CAJERO\000d\000aCREATE TABLE CAJERO (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del cajero',\000d\000a    NAME_CASHIER varchar(45)  NOT NULL COMMENT 'nombre del cajero',\000d\000a    NUMBER_BOX int  NOT NULL COMMENT 'numero de caja',\000d\000a    CONSTRAINT CAJERO_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'datos del cajero'"
Syntax error in SQL statement "-- Table: CAJERO\000d\000aCREATE TABLE CAJERO (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del cajero',\000d\000a    NAME_CASHIER varchar(45)  NOT NULL COMMENT 'nombre del cajero',\000d\000a    NUMBER_BOX int  NOT NULL COMMENT 'numero de caja',\000d\000a    CONSTRAINT CAJERO_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'datos del cajero'"; SQL statement:
-- Table: CAJERO
CREATE TABLE CAJERO (
    ID int  NOT NULL auto_increment COMMENT 'identificador del cajero',
    NAME_CASHIER varchar(45)  NOT NULL COMMENT 'nombre del cajero',
    NUMBER_BOX int  NOT NULL COMMENT 'numero de caja',
    CONSTRAINT CAJERO_pk PRIMARY KEY (ID)
) COMMENT 'datos del cajero' [42000-214]
2025-01-04 21:34:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: CLIENTE\000d\000aCREATE TABLE CLIENTE (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del cliente',\000d\000a    NAME_CUSTOMER varchar(45)  NOT NULL COMMENT 'nombre del cliente',\000d\000a    LAST_NAME varchar(45)  NOT NULL COMMENT 'apellido del cliente',\000d\000a    CONSTRAINT CLIENTE_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'datos del cliente'"
Syntax error in SQL statement "-- Table: CLIENTE\000d\000aCREATE TABLE CLIENTE (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del cliente',\000d\000a    NAME_CUSTOMER varchar(45)  NOT NULL COMMENT 'nombre del cliente',\000d\000a    LAST_NAME varchar(45)  NOT NULL COMMENT 'apellido del cliente',\000d\000a    CONSTRAINT CLIENTE_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'datos del cliente'"; SQL statement:
-- Table: CLIENTE
CREATE TABLE CLIENTE (
    ID int  NOT NULL auto_increment COMMENT 'identificador del cliente',
    NAME_CUSTOMER varchar(45)  NOT NULL COMMENT 'nombre del cliente',
    LAST_NAME varchar(45)  NOT NULL COMMENT 'apellido del cliente',
    CONSTRAINT CLIENTE_pk PRIMARY KEY (ID)
) COMMENT 'datos del cliente' [42000-214]
2025-01-04 21:34:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: DOCUMENTO_VENTA\000d\000aCREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del documento de venta',\000d\000a    AMOUNT double[*](10,2)  NOT NULL COMMENT 'monto del documento de venta',\000d\000a    TIME timestamp  NOT NULL COMMENT 'fecha de emisión',\000d\000a    TYPE char(1) not null,\000d\000a    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)\000d\000a) COMMENT 'datos principales del documento'"; se esperaba "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "-- Table: DOCUMENTO_VENTA\000d\000aCREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del documento de venta',\000d\000a    AMOUNT double[*](10,2)  NOT NULL COMMENT 'monto del documento de venta',\000d\000a    TIME timestamp  NOT NULL COMMENT 'fecha de emisión',\000d\000a    TYPE char(1) not null,\000d\000a    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)\000d\000a) COMMENT 'datos principales del documento'"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
-- Table: DOCUMENTO_VENTA
CREATE TABLE DOCUMENTO_VENTA (
    ID int  NOT NULL auto_increment COMMENT 'identificador del documento de venta',
    AMOUNT double(10,2)  NOT NULL COMMENT 'monto del documento de venta',
    TIME timestamp  NOT NULL COMMENT 'fecha de emisión',
    TYPE char(1) not null,
    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)
) COMMENT 'datos principales del documento' [42001-214]
2025-01-04 21:34:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: FACTURA\000d\000aCREATE TABLE FACTURA (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador de la factura',\000d\000a    SERIE int  NOT NULL COMMENT 'serie de la factura',\000d\000a    DOCUMENTO_VENTA_ID int  NOT NULL,\000d\000a    CONSTRAINT FACTURA_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'datos de la factura'"
Syntax error in SQL statement "-- Table: FACTURA\000d\000aCREATE TABLE FACTURA (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador de la factura',\000d\000a    SERIE int  NOT NULL COMMENT 'serie de la factura',\000d\000a    DOCUMENTO_VENTA_ID int  NOT NULL,\000d\000a    CONSTRAINT FACTURA_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'datos de la factura'"; SQL statement:
-- Table: FACTURA
CREATE TABLE FACTURA (
    ID int  NOT NULL auto_increment COMMENT 'identificador de la factura',
    SERIE int  NOT NULL COMMENT 'serie de la factura',
    DOCUMENTO_VENTA_ID int  NOT NULL,
    CONSTRAINT FACTURA_pk PRIMARY KEY (ID)
) COMMENT 'datos de la factura' [42000-214]
2025-01-04 21:34:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: PEDIDO\000d\000aCREATE TABLE PEDIDO (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'Identificador del pedido',\000d\000a    AMOUNT int  NOT NULL COMMENT 'cantidad ',\000d\000a    TIME timestamp  NOT NULL,\000d\000a    TRABAJADOR_ID int  NOT NULL,\000d\000a    PROVEEDOR_ID int  NOT NULL,\000d\000a    PRODUCTO_ID int  NOT NULL,\000d\000a    CONSTRAINT PEDIDO_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'registro de los pedidos'"
Syntax error in SQL statement "-- Table: PEDIDO\000d\000aCREATE TABLE PEDIDO (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'Identificador del pedido',\000d\000a    AMOUNT int  NOT NULL COMMENT 'cantidad ',\000d\000a    TIME timestamp  NOT NULL,\000d\000a    TRABAJADOR_ID int  NOT NULL,\000d\000a    PROVEEDOR_ID int  NOT NULL,\000d\000a    PRODUCTO_ID int  NOT NULL,\000d\000a    CONSTRAINT PEDIDO_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'registro de los pedidos'"; SQL statement:
-- Table: PEDIDO
CREATE TABLE PEDIDO (
    ID int  NOT NULL auto_increment COMMENT 'Identificador del pedido',
    AMOUNT int  NOT NULL COMMENT 'cantidad ',
    TIME timestamp  NOT NULL,
    TRABAJADOR_ID int  NOT NULL,
    PROVEEDOR_ID int  NOT NULL,
    PRODUCTO_ID int  NOT NULL,
    CONSTRAINT PEDIDO_pk PRIMARY KEY (ID)
) COMMENT 'registro de los pedidos' [42000-214]
2025-01-04 21:34:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: PRODUCTO\000d\000aCREATE TABLE PRODUCTO (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del producto',\000d\000a    NAME_PRODUC varchar(45)  NOT NULL COMMENT 'nombre del producto',\000d\000a    PRICE double[*](10,2)  NOT NULL COMMENT 'precio del producto',\000d\000a    AMOUNT int  NOT NULL COMMENT 'cantidad del producto',\000d\000a    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)\000d\000a) COMMENT 'datos de los productos'"; se esperaba "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "-- Table: PRODUCTO\000d\000aCREATE TABLE PRODUCTO (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del producto',\000d\000a    NAME_PRODUC varchar(45)  NOT NULL COMMENT 'nombre del producto',\000d\000a    PRICE double[*](10,2)  NOT NULL COMMENT 'precio del producto',\000d\000a    AMOUNT int  NOT NULL COMMENT 'cantidad del producto',\000d\000a    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)\000d\000a) COMMENT 'datos de los productos'"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    ID int  NOT NULL auto_increment COMMENT 'identificador del producto',
    NAME_PRODUC varchar(45)  NOT NULL COMMENT 'nombre del producto',
    PRICE double(10,2)  NOT NULL COMMENT 'precio del producto',
    AMOUNT int  NOT NULL COMMENT 'cantidad del producto',
    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)
) COMMENT 'datos de los productos' [42001-214]
2025-01-04 21:34:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: PROVEEDOR\000d\000aCREATE TABLE PROVEEDOR (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del proveedor',\000d\000a    RUC_E int  NOT NULL COMMENT 'RUC del proveedor',\000d\000a    NAME_COMPANY varchar(45)  NOT NULL COMMENT 'nombre de la compañía',\000d\000a    CONSTRAINT PROVEEDOR_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'registro de los proveedores'"
Syntax error in SQL statement "-- Table: PROVEEDOR\000d\000aCREATE TABLE PROVEEDOR (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del proveedor',\000d\000a    RUC_E int  NOT NULL COMMENT 'RUC del proveedor',\000d\000a    NAME_COMPANY varchar(45)  NOT NULL COMMENT 'nombre de la compañía',\000d\000a    CONSTRAINT PROVEEDOR_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'registro de los proveedores'"; SQL statement:
-- Table: PROVEEDOR
CREATE TABLE PROVEEDOR (
    ID int  NOT NULL auto_increment COMMENT 'identificador del proveedor',
    RUC_E int  NOT NULL COMMENT 'RUC del proveedor',
    NAME_COMPANY varchar(45)  NOT NULL COMMENT 'nombre de la compañía',
    CONSTRAINT PROVEEDOR_pk PRIMARY KEY (ID)
) COMMENT 'registro de los proveedores' [42000-214]
2025-01-04 21:34:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: TRABAJADOR\000d\000aCREATE TABLE TRABAJADOR (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del trabajador ',\000d\000a    NAME varchar(45)  NOT NULL COMMENT 'nombre del trabajador',\000d\000a    LAST_NAME varchar(45)  NOT NULL COMMENT 'apellido del trabajador',\000d\000a    CONSTRAINT TRABAJADOR_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'datos del trabajador'"
Syntax error in SQL statement "-- Table: TRABAJADOR\000d\000aCREATE TABLE TRABAJADOR (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador del trabajador ',\000d\000a    NAME varchar(45)  NOT NULL COMMENT 'nombre del trabajador',\000d\000a    LAST_NAME varchar(45)  NOT NULL COMMENT 'apellido del trabajador',\000d\000a    CONSTRAINT TRABAJADOR_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'datos del trabajador'"; SQL statement:
-- Table: TRABAJADOR
CREATE TABLE TRABAJADOR (
    ID int  NOT NULL auto_increment COMMENT 'identificador del trabajador ',
    NAME varchar(45)  NOT NULL COMMENT 'nombre del trabajador',
    LAST_NAME varchar(45)  NOT NULL COMMENT 'apellido del trabajador',
    CONSTRAINT TRABAJADOR_pk PRIMARY KEY (ID)
) COMMENT 'datos del trabajador' [42000-214]
2025-01-04 21:34:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: VENTA\000d\000aCREATE TABLE VENTA (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador de la venta',\000d\000a    AMOUNT_PRODUC int  NOT NULL,\000d\000a    TIME timestamp  NOT NULL COMMENT 'fecha de la venta',\000d\000a    CLIENTE_ID int  NOT NULL,\000d\000a    CAJERO_ID int  NOT NULL,\000d\000a    PRODUCTO_ID int  NOT NULL,\000d\000a    DOCUMENTO_VENTA_ID int  NOT NULL,\000d\000a    CONSTRAINT VENTA_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'registro de las ventas'"
Syntax error in SQL statement "-- Table: VENTA\000d\000aCREATE TABLE VENTA (\000d\000a    ID int  NOT NULL auto_increment COMMENT 'identificador de la venta',\000d\000a    AMOUNT_PRODUC int  NOT NULL,\000d\000a    TIME timestamp  NOT NULL COMMENT 'fecha de la venta',\000d\000a    CLIENTE_ID int  NOT NULL,\000d\000a    CAJERO_ID int  NOT NULL,\000d\000a    PRODUCTO_ID int  NOT NULL,\000d\000a    DOCUMENTO_VENTA_ID int  NOT NULL,\000d\000a    CONSTRAINT VENTA_pk PRIMARY KEY (ID)\000d\000a) [*]COMMENT 'registro de las ventas'"; SQL statement:
-- Table: VENTA
CREATE TABLE VENTA (
    ID int  NOT NULL auto_increment COMMENT 'identificador de la venta',
    AMOUNT_PRODUC int  NOT NULL,
    TIME timestamp  NOT NULL COMMENT 'fecha de la venta',
    CLIENTE_ID int  NOT NULL,
    CAJERO_ID int  NOT NULL,
    PRODUCTO_ID int  NOT NULL,
    DOCUMENTO_VENTA_ID int  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (ID)
) COMMENT 'registro de las ventas' [42000-214]
2025-01-04 21:34:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- foreign keys\000d\000a-- Reference: BOLETA_DOCUMENTO_VENTA (table: BOLETA)\000d\000aALTER TABLE BOLETA ADD CONSTRAINT BOLETA_DOCUMENTO_VENTA FOREIGN KEY [*]BOLETA_DOCUMENTO_VENTA (DOCUMENTO_VENTA_ID)\000d\000a    REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON UPDATE CASCADE"; se esperaba "("
Syntax error in SQL statement "-- foreign keys\000d\000a-- Reference: BOLETA_DOCUMENTO_VENTA (table: BOLETA)\000d\000aALTER TABLE BOLETA ADD CONSTRAINT BOLETA_DOCUMENTO_VENTA FOREIGN KEY [*]BOLETA_DOCUMENTO_VENTA (DOCUMENTO_VENTA_ID)\000d\000a    REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON UPDATE CASCADE"; expected "("; SQL statement:
-- foreign keys
-- Reference: BOLETA_DOCUMENTO_VENTA (table: BOLETA)
ALTER TABLE BOLETA ADD CONSTRAINT BOLETA_DOCUMENTO_VENTA FOREIGN KEY BOLETA_DOCUMENTO_VENTA (DOCUMENTO_VENTA_ID)
    REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON UPDATE CASCADE [42001-214]
2025-01-04 21:34:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Reference: FACTURA_DOCUMENTO_VENTA (table: FACTURA)\000d\000aALTER TABLE FACTURA ADD CONSTRAINT FACTURA_DOCUMENTO_VENTA FOREIGN KEY [*]FACTURA_DOCUMENTO_VENTA (DOCUMENTO_VENTA_ID)\000d\000a    REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON UPDATE CASCADE"; se esperaba "("
Syntax error in SQL statement "-- Reference: FACTURA_DOCUMENTO_VENTA (table: FACTURA)\000d\000aALTER TABLE FACTURA ADD CONSTRAINT FACTURA_DOCUMENTO_VENTA FOREIGN KEY [*]FACTURA_DOCUMENTO_VENTA (DOCUMENTO_VENTA_ID)\000d\000a    REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON UPDATE CASCADE"; expected "("; SQL statement:
-- Reference: FACTURA_DOCUMENTO_VENTA (table: FACTURA)
ALTER TABLE FACTURA ADD CONSTRAINT FACTURA_DOCUMENTO_VENTA FOREIGN KEY FACTURA_DOCUMENTO_VENTA (DOCUMENTO_VENTA_ID)
    REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON UPDATE CASCADE [42001-214]
2025-01-04 21:34:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Reference: PEDIDO_PRODUCTO (table: PEDIDO)\000d\000aALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_PRODUCTO FOREIGN KEY [*]PEDIDO_PRODUCTO (PRODUCTO_ID)\000d\000a    REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON UPDATE CASCADE"; se esperaba "("
Syntax error in SQL statement "-- Reference: PEDIDO_PRODUCTO (table: PEDIDO)\000d\000aALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_PRODUCTO FOREIGN KEY [*]PEDIDO_PRODUCTO (PRODUCTO_ID)\000d\000a    REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON UPDATE CASCADE"; expected "("; SQL statement:
-- Reference: PEDIDO_PRODUCTO (table: PEDIDO)
ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_PRODUCTO FOREIGN KEY PEDIDO_PRODUCTO (PRODUCTO_ID)
    REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON UPDATE CASCADE [42001-214]
2025-01-04 21:34:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Reference: PEDIDO_PROVEEDOR (table: PEDIDO)\000d\000aALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_PROVEEDOR FOREIGN KEY [*]PEDIDO_PROVEEDOR (PROVEEDOR_ID)\000d\000a    REFERENCES PROVEEDOR (ID) ON DELETE CASCADE ON UPDATE CASCADE"; se esperaba "("
Syntax error in SQL statement "-- Reference: PEDIDO_PROVEEDOR (table: PEDIDO)\000d\000aALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_PROVEEDOR FOREIGN KEY [*]PEDIDO_PROVEEDOR (PROVEEDOR_ID)\000d\000a    REFERENCES PROVEEDOR (ID) ON DELETE CASCADE ON UPDATE CASCADE"; expected "("; SQL statement:
-- Reference: PEDIDO_PROVEEDOR (table: PEDIDO)
ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_PROVEEDOR FOREIGN KEY PEDIDO_PROVEEDOR (PROVEEDOR_ID)
    REFERENCES PROVEEDOR (ID) ON DELETE CASCADE ON UPDATE CASCADE [42001-214]
2025-01-04 21:34:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Reference: PEDIDO_TRABAJADOR (table: PEDIDO)\000d\000aALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_TRABAJADOR FOREIGN KEY [*]PEDIDO_TRABAJADOR (TRABAJADOR_ID)\000d\000a    REFERENCES TRABAJADOR (ID) ON DELETE CASCADE ON UPDATE CASCADE"; se esperaba "("
Syntax error in SQL statement "-- Reference: PEDIDO_TRABAJADOR (table: PEDIDO)\000d\000aALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_TRABAJADOR FOREIGN KEY [*]PEDIDO_TRABAJADOR (TRABAJADOR_ID)\000d\000a    REFERENCES TRABAJADOR (ID) ON DELETE CASCADE ON UPDATE CASCADE"; expected "("; SQL statement:
-- Reference: PEDIDO_TRABAJADOR (table: PEDIDO)
ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_TRABAJADOR FOREIGN KEY PEDIDO_TRABAJADOR (TRABAJADOR_ID)
    REFERENCES TRABAJADOR (ID) ON DELETE CASCADE ON UPDATE CASCADE [42001-214]
2025-01-04 21:34:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Reference: VENTA_CAJERO (table: VENTA)\000d\000aALTER TABLE VENTA ADD CONSTRAINT VENTA_CAJERO FOREIGN KEY [*]VENTA_CAJERO (CAJERO_ID)\000d\000a    REFERENCES CAJERO (ID) ON DELETE CASCADE ON UPDATE CASCADE"; se esperaba "("
Syntax error in SQL statement "-- Reference: VENTA_CAJERO (table: VENTA)\000d\000aALTER TABLE VENTA ADD CONSTRAINT VENTA_CAJERO FOREIGN KEY [*]VENTA_CAJERO (CAJERO_ID)\000d\000a    REFERENCES CAJERO (ID) ON DELETE CASCADE ON UPDATE CASCADE"; expected "("; SQL statement:
-- Reference: VENTA_CAJERO (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_CAJERO FOREIGN KEY VENTA_CAJERO (CAJERO_ID)
    REFERENCES CAJERO (ID) ON DELETE CASCADE ON UPDATE CASCADE [42001-214]
2025-01-04 21:34:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Reference: VENTA_CLIENTE (table: VENTA)\000d\000aALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE FOREIGN KEY [*]VENTA_CLIENTE (CLIENTE_ID)\000d\000a    REFERENCES CLIENTE (ID) ON DELETE CASCADE ON UPDATE CASCADE"; se esperaba "("
Syntax error in SQL statement "-- Reference: VENTA_CLIENTE (table: VENTA)\000d\000aALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE FOREIGN KEY [*]VENTA_CLIENTE (CLIENTE_ID)\000d\000a    REFERENCES CLIENTE (ID) ON DELETE CASCADE ON UPDATE CASCADE"; expected "("; SQL statement:
-- Reference: VENTA_CLIENTE (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE FOREIGN KEY VENTA_CLIENTE (CLIENTE_ID)
    REFERENCES CLIENTE (ID) ON DELETE CASCADE ON UPDATE CASCADE [42001-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Reference: VENTA_DOCUMENTO_VENTA (table: VENTA)\000d\000aALTER TABLE VENTA ADD CONSTRAINT VENTA_DOCUMENTO_VENTA FOREIGN KEY [*]VENTA_DOCUMENTO_VENTA (DOCUMENTO_VENTA_ID)\000d\000a    REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON UPDATE CASCADE"; se esperaba "("
Syntax error in SQL statement "-- Reference: VENTA_DOCUMENTO_VENTA (table: VENTA)\000d\000aALTER TABLE VENTA ADD CONSTRAINT VENTA_DOCUMENTO_VENTA FOREIGN KEY [*]VENTA_DOCUMENTO_VENTA (DOCUMENTO_VENTA_ID)\000d\000a    REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON UPDATE CASCADE"; expected "("; SQL statement:
-- Reference: VENTA_DOCUMENTO_VENTA (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_DOCUMENTO_VENTA FOREIGN KEY VENTA_DOCUMENTO_VENTA (DOCUMENTO_VENTA_ID)
    REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON UPDATE CASCADE [42001-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Reference: VENTA_PRODUCTO (table: VENTA)\000d\000aALTER TABLE VENTA ADD CONSTRAINT VENTA_PRODUCTO FOREIGN KEY [*]VENTA_PRODUCTO (PRODUCTO_ID)\000d\000a    REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON UPDATE CASCADE"; se esperaba "("
Syntax error in SQL statement "-- Reference: VENTA_PRODUCTO (table: VENTA)\000d\000aALTER TABLE VENTA ADD CONSTRAINT VENTA_PRODUCTO FOREIGN KEY [*]VENTA_PRODUCTO (PRODUCTO_ID)\000d\000a    REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON UPDATE CASCADE"; expected "("; SQL statement:
-- Reference: VENTA_PRODUCTO (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_PRODUCTO FOREIGN KEY VENTA_PRODUCTO (PRODUCTO_ID)
    REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON UPDATE CASCADE [42001-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CLIENTE" not found (this database is empty); SQL statement:
insert into CLIENTE ( NAME_CUSTOMER, LAST_NAME)
values ('Cristopher', 'sotelo'),
('	Ronald', 'Espinoza') [42104-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CAJERO" not found (this database is empty); SQL statement:
insert into CAJERO ( NAME_CASHIER, NUMBER_BOX)
VALUES( 'Paola', '3'),
      ( 'Jorge', '2') [42104-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PRODUCTO" not found (this database is empty); SQL statement:
insert into PRODUCTO ( NAME_PRODUC, PRICE, AMOUNT)
VALUES( 'fideo', 5.4, '20'),
      ('leche', 4.2, '15') [42104-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TRABAJADOR" not found (this database is empty); SQL statement:
insert into TRABAJADOR ( NAME, LAST_NAME)
values ( 'Rosa', 'Linares'),
( 'Pedro', 'Yactayo') [42104-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PROVEEDOR" not found (this database is empty); SQL statement:
insert into PROVEEDOR ( RUC_E, NAME_COMPANY)
values ( '2015678954', 'ARCOR'),
('	2046379345', 'Nestle') [42104-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PEDIDO" not found (this database is empty); SQL statement:
insert into PEDIDO ( AMOUNT, TIME, TRABAJADOR_ID, PROVEEDOR_ID, PRODUCTO_ID)
values ('22', '2024-11-08 10:00:00', '0001', '00001',0002),
       ( '13','2024-11-08 11:35:06', '0002', '00002',0001) [42104-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "DOCUMENTO_VENTA" not found (this database is empty); SQL statement:
insert into DOCUMENTO_VENTA ( AMOUNT, TIME, TYPE)
values ( '11', '2024-11-07 09:12:36', 'B'),
       ( '8','2024-11-07 10:34:29','F'),
       ( '20', '2024-11-07 11:12:36', 'B'),
       ( '18','2024-11-07 12:34:29','F') [42104-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "VENTA" not found (this database is empty); SQL statement:
insert into VENTA ( AMOUNT_PRODUC, TIME, CLIENTE_ID, CAJERO_ID, PRODUCTO_ID, DOCUMENTO_VENTA_ID)
values ( '2', '2024-11-07 09:16:06', '2', '01', '002', '02'),
       ( '3','2024-11-07 10:40:19', '1', '02', '001', '01') [42104-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "BOLETA" not found (this database is empty); SQL statement:
insert into BOLETA ( NUMBER_TICKET, DOCUMENTO_VENTA_ID)
values ( '645', '2'),
       ( '3', '1') [42104-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "BOLETA" not found (this database is empty); SQL statement:
insert into BOLETA ( NUMBER_TICKET, DOCUMENTO_VENTA_ID)
values        ( '5', '11') [42104-214]
2025-01-04 21:34:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "FACTURA" not found (this database is empty); SQL statement:
insert into FACTURA ( SERIE, DOCUMENTO_VENTA_ID)
values ('2468', '2'),
       ( '3742', '1') [42104-214]
2025-01-04 21:56:29 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "DOCUMENTO_VENTA" no encontrada
Table "DOCUMENTO_VENTA" not found; SQL statement:
CREATE TABLE FACTURA (
    ID int  NOT NULL auto_increment,
    SERIE int  NOT NULL,
    DOCUMENTO_VENTA_ID int  NOT NULL,
FOREIGN KEY (DOCUMENTO_VENTA_ID) REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FACTURA_pk PRIMARY KEY (ID)
) [42102-214]
2025-01-04 22:12:47 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "CREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID int  NOT NULL auto_increment,\000d\000a    AMOUNT double[*](10,2)  NOT NULL,\000d\000a    TIME timestamp  NOT NULL,\000d\000a    TYPE char(1) not null,\000d\000a\000d\000a    PRIMARY KEY (ID)\000d\000a)"; se esperaba "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "CREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID int  NOT NULL auto_increment,\000d\000a    AMOUNT double[*](10,2)  NOT NULL,\000d\000a    TIME timestamp  NOT NULL,\000d\000a    TYPE char(1) not null,\000d\000a\000d\000a    PRIMARY KEY (ID)\000d\000a)"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE DOCUMENTO_VENTA (
    ID int  NOT NULL auto_increment,
    AMOUNT double(10,2)  NOT NULL,
    TIME timestamp  NOT NULL,
    TYPE char(1) not null,

    PRIMARY KEY (ID)
) [42001-214]
2025-01-04 22:13:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "BOLETA" ya existe
Table "BOLETA" already exists; SQL statement:
CREATE TABLE BOLETA (
    ID int  NOT NULL auto_increment,
    NUMBER_TICKET int  NOT NULL,
    DOCUMENTO_VENTA_ID int  NOT NULL,
FOREIGN KEY (DOCUMENTO_VENTA_ID)  REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT BOLETA_pk PRIMARY KEY (ID)

) [42101-214]
2025-01-04 22:14:11 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "CREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID int  NOT NULL auto_increment,\000d\000a    AMOUNT double[*](10,2)  NOT NULL,\000d\000a    TIME timestamp  NOT NULL,\000d\000a    TYPE char(1) not null,\000d\000a    PRIMARY KEY (ID)\000d\000a)"; se esperaba "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "CREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID int  NOT NULL auto_increment,\000d\000a    AMOUNT double[*](10,2)  NOT NULL,\000d\000a    TIME timestamp  NOT NULL,\000d\000a    TYPE char(1) not null,\000d\000a    PRIMARY KEY (ID)\000d\000a)"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE DOCUMENTO_VENTA (
    ID int  NOT NULL auto_increment,
    AMOUNT double(10,2)  NOT NULL,
    TIME timestamp  NOT NULL,
    TYPE char(1) not null,
    PRIMARY KEY (ID)
) [42001-214]
2025-01-04 22:24:05 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "DOCUMENTO_VENTA" no encontrada
Table "DOCUMENTO_VENTA" not found; SQL statement:
-- Table: BOLETA
CREATE TABLE BOLETA (
    ID INT NOT NULL AUTO_INCREMENT,
    NUMBER_TICKET INT NOT NULL,
    DOCUMENTO_VENTA_ID INT NOT NULL,
    CONSTRAINT BOLETA_pk PRIMARY KEY (ID),
    CONSTRAINT BOLETA_DOCUMENTO_VENTA FOREIGN KEY (DOCUMENTO_VENTA_ID)
        REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON [42102-214]
2025-01-04 22:24:05 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: DOCUMENTO_VENTA\000d\000aCREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT DOUBLE[*](10,2) NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    TYPE CHAR(1) NOT NULL,\000d\000a    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)\000d\000a)"; se esperaba "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "-- Table: DOCUMENTO_VENTA\000d\000aCREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT DOUBLE[*](10,2) NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    TYPE CHAR(1) NOT NULL,\000d\000a    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)\000d\000a)"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
-- Table: DOCUMENTO_VENTA
CREATE TABLE DOCUMENTO_VENTA (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT DOUBLE(10,2) NOT NULL,
    TIME TIMESTAMP NOT NULL,
    TYPE CHAR(1) NOT NULL,
    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)
) [42001-214]
2025-01-04 22:24:05 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "DOCUMENTO_VENTA" no encontrada
Table "DOCUMENTO_VENTA" not found; SQL statement:
-- Table: FACTURA
CREATE TABLE FACTURA (
    ID INT NOT NULL AUTO_INCREMENT,
    SERIE INT NOT NULL,
    DOCUMENTO_VENTA_ID INT NOT NULL,
    CONSTRAINT FACTURA_pk PRIMARY KEY (ID),
    CONSTRAINT FACTURA_DOCUMENTO_VENTA FOREIGN KEY (DOCUMENTO_VENTA_ID)
        REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE O [42102-214]
2025-01-04 22:24:06 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "TRABAJADOR" no encontrada
Table "TRABAJADOR" not found; SQL statement:
-- Table: PEDIDO
CREATE TABLE PEDIDO (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT INT NOT NULL,
    TIME TIMESTAMP NOT NULL,
    TRABAJADOR_ID INT NOT NULL,
    PROVEEDOR_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    CONSTRAINT PEDIDO_pk PRIMARY KEY (ID),
    CONSTRAINT PEDIDO_TRABAJADOR FOREIGN KEY (TRABAJADOR_ID)
        REFERENCES TRABAJADOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PEDIDO_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID)
        REFERENCES PROVEEDOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PEDIDO_PRODUCTO FOREIGN KEY (PRODUCTO_ID)
        REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON [42102-214]
2025-01-04 22:24:06 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: PRODUCTO\000d\000aCREATE TABLE PRODUCTO (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    NAME_PRODUC VARCHAR(45) NOT NULL,\000d\000a    PRICE DOUBLE[*](10,2) NOT NULL,\000d\000a    AMOUNT INT NOT NULL,\000d\000a    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)\000d\000a)"; se esperaba "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "-- Table: PRODUCTO\000d\000aCREATE TABLE PRODUCTO (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    NAME_PRODUC VARCHAR(45) NOT NULL,\000d\000a    PRICE DOUBLE[*](10,2) NOT NULL,\000d\000a    AMOUNT INT NOT NULL,\000d\000a    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)\000d\000a)"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME_PRODUC VARCHAR(45) NOT NULL,
    PRICE DOUBLE(10,2) NOT NULL,
    AMOUNT INT NOT NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)
) [42001-214]
2025-01-04 22:24:06 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "PRODUCTO" no encontrada
Table "PRODUCTO" not found; SQL statement:
-- Table: VENTA
CREATE TABLE VENTA (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT_PRODUC INT NOT NULL,
    TIME TIMESTAMP NOT NULL,
    CLIENTE_ID INT NOT NULL,
    CAJERO_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    DOCUMENTO_VENTA_ID INT NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (ID),
    CONSTRAINT VENTA_CLIENTE FOREIGN KEY (CLIENTE_ID)
        REFERENCES CLIENTE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT VENTA_CAJERO FOREIGN KEY (CAJERO_ID)
        REFERENCES CAJERO (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT VENTA_PRODUCTO FOREIGN KEY (PRODUCTO_ID)
        REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT VENTA_DOCUMENTO_VENTA FOREIGN KEY (DOCUMENTO_VENTA_ID)
        REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON  [42102-214]
2025-01-04 22:25:45 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: DOCUMENTO_VENTA\000d\000aCREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT DOUBLE[*](10,2) NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    TYPE CHAR(1) NOT NULL,\000d\000a    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)\000d\000a)"; se esperaba "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "-- Table: DOCUMENTO_VENTA\000d\000aCREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT DOUBLE[*](10,2) NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    TYPE CHAR(1) NOT NULL,\000d\000a    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)\000d\000a)"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
-- Table: DOCUMENTO_VENTA
CREATE TABLE DOCUMENTO_VENTA (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT DOUBLE(10,2) NOT NULL,
    TIME TIMESTAMP NOT NULL,
    TYPE CHAR(1) NOT NULL,
    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)
) [42001-214]
2025-01-04 22:25:47 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: DOCUMENTO_VENTA\000d\000aCREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT DOUBLE[*](10,2) NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    TYPE CHAR(1) NOT NULL,\000d\000a    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)\000d\000a)"; se esperaba "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "-- Table: DOCUMENTO_VENTA\000d\000aCREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT DOUBLE[*](10,2) NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    TYPE CHAR(1) NOT NULL,\000d\000a    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)\000d\000a)"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
-- Table: DOCUMENTO_VENTA
CREATE TABLE DOCUMENTO_VENTA (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT DOUBLE(10,2) NOT NULL,
    TIME TIMESTAMP NOT NULL,
    TYPE CHAR(1) NOT NULL,
    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)
) [42001-214]
2025-01-04 22:26:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: DOCUMENTO_VENTA\000d\000aCREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT DOUBLE[*](10,2) NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    TYPE CHAR(1) NOT NULL,\000d\000a    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)\000d\000a)"; se esperaba "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "-- Table: DOCUMENTO_VENTA\000d\000aCREATE TABLE DOCUMENTO_VENTA (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT DOUBLE[*](10,2) NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    TYPE CHAR(1) NOT NULL,\000d\000a    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)\000d\000a)"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
-- Table: DOCUMENTO_VENTA
CREATE TABLE DOCUMENTO_VENTA (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT DOUBLE(10,2) NOT NULL,
    TIME TIMESTAMP NOT NULL,
    TYPE CHAR(1) NOT NULL,
    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)
) [42001-214]
2025-01-04 22:26:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "DOCUMENTO_VENTA" no encontrada
Table "DOCUMENTO_VENTA" not found; SQL statement:
-- Table: BOLETA
CREATE TABLE BOLETA (
    ID INT NOT NULL AUTO_INCREMENT,
    NUMBER_TICKET INT NOT NULL,
    DOCUMENTO_VENTA_ID INT NOT NULL,
    CONSTRAINT BOLETA_pk PRIMARY KEY (ID),
    CONSTRAINT BOLETA_DOCUMENTO_VENTA FOREIGN KEY (DOCUMENTO_VENTA_ID)
        REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON [42102-214]
2025-01-04 22:26:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "DOCUMENTO_VENTA" no encontrada
Table "DOCUMENTO_VENTA" not found; SQL statement:
-- Table: FACTURA
CREATE TABLE FACTURA (
    ID INT NOT NULL AUTO_INCREMENT,
    SERIE INT NOT NULL,
    DOCUMENTO_VENTA_ID INT NOT NULL,
    CONSTRAINT FACTURA_pk PRIMARY KEY (ID),
    CONSTRAINT FACTURA_DOCUMENTO_VENTA FOREIGN KEY (DOCUMENTO_VENTA_ID)
        REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE O [42102-214]
2025-01-04 22:26:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: PRODUCTO\000d\000aCREATE TABLE PRODUCTO (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    NAME_PRODUC VARCHAR(45) NOT NULL,\000d\000a    PRICE DOUBLE[*](10,2) NOT NULL,\000d\000a    AMOUNT INT NOT NULL,\000d\000a    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)\000d\000a)"; se esperaba "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "-- Table: PRODUCTO\000d\000aCREATE TABLE PRODUCTO (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    NAME_PRODUC VARCHAR(45) NOT NULL,\000d\000a    PRICE DOUBLE[*](10,2) NOT NULL,\000d\000a    AMOUNT INT NOT NULL,\000d\000a    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)\000d\000a)"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME_PRODUC VARCHAR(45) NOT NULL,
    PRICE DOUBLE(10,2) NOT NULL,
    AMOUNT INT NOT NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)
) [42001-214]
2025-01-04 22:26:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "PRODUCTO" no encontrada
Table "PRODUCTO" not found; SQL statement:
-- Table: PEDIDO
CREATE TABLE PEDIDO (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT INT NOT NULL,
    TIME TIMESTAMP NOT NULL,
    TRABAJADOR_ID INT NOT NULL,
    PROVEEDOR_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    CONSTRAINT PEDIDO_pk PRIMARY KEY (ID),
    CONSTRAINT PEDIDO_TRABAJADOR FOREIGN KEY (TRABAJADOR_ID)
        REFERENCES TRABAJADOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PEDIDO_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID)
        REFERENCES PROVEEDOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PEDIDO_PRODUCTO FOREIGN KEY (PRODUCTO_ID)
        REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON [42102-214]
2025-01-04 22:26:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: VENTA\000d\000aCREATE TABLE VENTA (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT_PRODUC INT NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    CLIENTE_ID INT NOT NULL,\000d\000a    CAJERO_ID INT NOT NULL,\000d\000a    PRODUCTO_ID INT NOT NULL,\000d\000a    DOCUMENTO_VENTA_ID INT NOT NULL,\000d\000a    CONSTRAINT VENTA_pk PRIMARY KEY (ID),\000d\000a    CONSTRAINT VENTA_CLIENTE [*]FO"; se esperaba "., COMMENT, PRIMARY, UNIQUE, FOREIGN, CHECK"
Syntax error in SQL statement "-- Table: VENTA\000d\000aCREATE TABLE VENTA (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT_PRODUC INT NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    CLIENTE_ID INT NOT NULL,\000d\000a    CAJERO_ID INT NOT NULL,\000d\000a    PRODUCTO_ID INT NOT NULL,\000d\000a    DOCUMENTO_VENTA_ID INT NOT NULL,\000d\000a    CONSTRAINT VENTA_pk PRIMARY KEY (ID),\000d\000a    CONSTRAINT VENTA_CLIENTE [*]FO"; expected "., COMMENT, PRIMARY, UNIQUE, FOREIGN, CHECK"; SQL statement:
-- Table: VENTA
CREATE TABLE VENTA (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT_PRODUC INT NOT NULL,
    TIME TIMESTAMP NOT NULL,
    CLIENTE_ID INT NOT NULL,
    CAJERO_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    DOCUMENTO_VENTA_ID INT NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (ID),
    CONSTRAINT VENTA_CLIENTE FO [42001-214]
2025-01-04 22:29:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "DOCUMENTO_VENTA" ya existe
Table "DOCUMENTO_VENTA" already exists; SQL statement:
CREATE TABLE DOCUMENTO_VENTA (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT DECIMAL(10,2) NOT NULL, 
    TIME TIMESTAMP NOT NULL,
    TYPE CHAR(1) NOT NULL,
    CONSTRAINT DOCUMENTO_VENTA_pk PRIMARY KEY (ID)
) [42101-214]
2025-01-04 22:30:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "-- Table: PRODUCTO\000d\000aCREATE TABLE PRODUCTO (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    NAME_PRODUC VARCHAR(45) NOT NULL,\000d\000a    PRICE DOUBLE[*](10,2) NOT NULL,\000d\000a    AMOUNT INT NOT NULL,\000d\000a    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)\000d\000a)"; se esperaba "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "-- Table: PRODUCTO\000d\000aCREATE TABLE PRODUCTO (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    NAME_PRODUC VARCHAR(45) NOT NULL,\000d\000a    PRICE DOUBLE[*](10,2) NOT NULL,\000d\000a    AMOUNT INT NOT NULL,\000d\000a    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)\000d\000a)"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME_PRODUC VARCHAR(45) NOT NULL,
    PRICE DOUBLE(10,2) NOT NULL,
    AMOUNT INT NOT NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY (ID)
) [42001-214]
2025-01-04 22:30:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "PRODUCTO" no encontrada
Table "PRODUCTO" not found; SQL statement:
-- Table: PEDIDO
CREATE TABLE PEDIDO (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT INT NOT NULL,
    TIME TIMESTAMP NOT NULL,
    TRABAJADOR_ID INT NOT NULL,
    PROVEEDOR_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    CONSTRAINT PEDIDO_pk PRIMARY KEY (ID),
    CONSTRAINT PEDIDO_TRABAJADOR FOREIGN KEY (TRABAJADOR_ID)
        REFERENCES TRABAJADOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PEDIDO_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID)
        REFERENCES PROVEEDOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PEDIDO_PRODUCTO FOREIGN KEY (PRODUCTO_ID)
        REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON [42102-214]
2025-01-04 22:30:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "PRODUCTO" no encontrada
Table "PRODUCTO" not found; SQL statement:
-- Table: VENTA
CREATE TABLE VENTA (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT_PRODUC INT NOT NULL,
    TIME TIMESTAMP NOT NULL,
    CLIENTE_ID INT NOT NULL,
    CAJERO_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    DOCUMENTO_VENTA_ID INT NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (ID),
    CONSTRAINT VENTA_CLIENTE FOREIGN KEY (CLIENTE_ID)
        REFERENCES CLIENTE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT VENTA_CAJERO FOREIGN KEY (CAJERO_ID)
        REFERENCES CAJERO (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT VENTA_PRODUCTO FOREIGN KEY (PRODUCTO_ID)
        REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT VENTA_DOCUMENTO_VENTA FOREIGN KEY (DOCUMENTO_VENTA_ID)
        REFERENCES DOCUMENTO_VENTA (ID) ON DELETE CASCADE ON  [42102-214]
2025-01-04 22:31:13 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "Table[*]: PEDIDO\000d\000aCREATE TABLE PEDIDO (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT INT NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    TRABAJADOR_ID INT NOT NULL,\000d\000a    PROVEEDOR_ID INT NOT NULL,\000d\000a    PRODUCTO_ID INT NOT NULL,\000d\000a    CONSTRAINT PEDIDO_pk PRIMARY KEY (ID),\000d\000a    CONSTRAINT PEDIDO_TRABAJADOR FOREIGN KEY (TRABAJADOR_ID)\000d\000a        REFERENCES TRABAJADOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,\000d\000a    CONSTRAINT PEDIDO_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID)\000d\000a        REFERENCES PROVEEDOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,\000d\000a    CONSTRAINT PEDIDO_PRODUCTO FOREIGN KEY (PRODUCTO_ID)\000d\000a        REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON UPDATE CASCADE\000d\000a)"; se esperaba "identifier"
Syntax error in SQL statement "Table[*]: PEDIDO\000d\000aCREATE TABLE PEDIDO (\000d\000a    ID INT NOT NULL AUTO_INCREMENT,\000d\000a    AMOUNT INT NOT NULL,\000d\000a    TIME TIMESTAMP NOT NULL,\000d\000a    TRABAJADOR_ID INT NOT NULL,\000d\000a    PROVEEDOR_ID INT NOT NULL,\000d\000a    PRODUCTO_ID INT NOT NULL,\000d\000a    CONSTRAINT PEDIDO_pk PRIMARY KEY (ID),\000d\000a    CONSTRAINT PEDIDO_TRABAJADOR FOREIGN KEY (TRABAJADOR_ID)\000d\000a        REFERENCES TRABAJADOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,\000d\000a    CONSTRAINT PEDIDO_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID)\000d\000a        REFERENCES PROVEEDOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,\000d\000a    CONSTRAINT PEDIDO_PRODUCTO FOREIGN KEY (PRODUCTO_ID)\000d\000a        REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON UPDATE CASCADE\000d\000a)"; expected "identifier"; SQL statement:
Table: PEDIDO
CREATE TABLE PEDIDO (
    ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT INT NOT NULL,
    TIME TIMESTAMP NOT NULL,
    TRABAJADOR_ID INT NOT NULL,
    PROVEEDOR_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    CONSTRAINT PEDIDO_pk PRIMARY KEY (ID),
    CONSTRAINT PEDIDO_TRABAJADOR FOREIGN KEY (TRABAJADOR_ID)
        REFERENCES TRABAJADOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PEDIDO_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID)
        REFERENCES PROVEEDOR (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PEDIDO_PRODUCTO FOREIGN KEY (PRODUCTO_ID)
        REFERENCES PRODUCTO (ID) ON DELETE CASCADE ON UPDATE CASCADE
) [42001-214]
2025-01-05 20:29:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "SELECT * FROM [*]all table"; se esperaba "identifier"
Syntax error in SQL statement "SELECT * FROM [*]all table"; expected "identifier"; SQL statement:
SELECT * FROM all table [42001-214]
2025-01-05 20:36:38 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dao.Coneccion.conectar(Coneccion.java:26)
	at dao.VentaImpl.modificar(VentaImpl.java:45)
	at TestVentaImpl.testModificar(TestVentaImpl.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 56 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 50 more
2025-01-05 22:54:44 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dao.Coneccion.conectar(Coneccion.java:26)
	at dao.VentaImpl.modificar(VentaImpl.java:45)
	at TestVentaImpl.testModificar(TestVentaImpl.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 56 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 50 more
2025-01-05 22:55:06 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dao.Coneccion.conectar(Coneccion.java:26)
	at dao.VentaImpl.registrar(VentaImpl.java:27)
	at TestVentaImpl.testRegistrar(TestVentaImpl.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 56 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 50 more
2025-01-05 23:16:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dao.Coneccion.conectar(Coneccion.java:26)
	at dao.VentaImpl.registrar(VentaImpl.java:27)
	at TestVentaImpl.testRegistrar(TestVentaImpl.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 56 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 50 more
2025-01-05 23:19:22 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dao.Coneccion.conectar(Coneccion.java:26)
	at dao.VentaImpl.registrar(VentaImpl.java:27)
	at TestVentaImpl.testRegistrar(TestVentaImpl.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 56 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 50 more
2025-01-06 21:47:11 database: wrong user or password; user: "ROOT"
org.h2.message.DbException: Nombre de usuario ó password incorrecto
Wrong user name or password [28000-214]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.engine.Engine.openSession(Engine.java:154)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dao.Coneccion.conectar(Coneccion.java:26)
	at dao.VentaImpl.registrar(VentaImpl.java:27)
	at TestVentaImpl.testRegistrar(TestVentaImpl.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Nombre de usuario ó password incorrecto
Wrong user name or password [28000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:510)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 50 more
2025-01-08 21:30:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "select * from [*]all table"; se esperaba "identifier"
Syntax error in SQL statement "select * from [*]all table"; expected "identifier"; SQL statement:
select * from all table [42001-214]
2025-01-08 21:58:26 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dao.Coneccion.conectar(Coneccion.java:26)
	at dao.VentaImpl.registrar(VentaImpl.java:27)
	at TestVentaImpl.testRegistrar(TestVentaImpl.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 56 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 50 more
2025-01-08 22:08:18 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dao.Coneccion.conectar(Coneccion.java:26)
	at dao.VentaImpl.registrar(VentaImpl.java:27)
	at TestVentaImpl.testRegistrar(TestVentaImpl.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 56 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 50 more
2025-01-12 09:09:29 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dao.Coneccion.conectar(Coneccion.java:26)
	at dao.PedidoImpl.registrar(PedidoImpl.java:23)
	at TestPedidoImpl.testRegistrar(TestPedidoImpl.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 56 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 50 more
2025-01-12 09:10:27 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dao.Coneccion.conectar(Coneccion.java:26)
	at dao.PedidoImpl.registrar(PedidoImpl.java:23)
	at TestPedidoImpl.testRegistrar(TestPedidoImpl.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 56 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 50 more
2025-01-12 09:11:49 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dao.Coneccion.conectar(Coneccion.java:26)
	at dao.PedidoImpl.registrar(PedidoImpl.java:23)
	at TestPedidoImpl.testRegistrar(TestPedidoImpl.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 56 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: D:/PROYECTOS/MIXMARKET/base/base.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 50 more
